# Generated by Django 5.0.4 on 2024-04-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solvators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.CharField(max_length=255, null=True, unique=True)),
                ("description", models.TextField()),
                ("time", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.CharField(max_length=255, null=True, unique=True)),
                ("description", models.TextField()),
                ("time", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="empid",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
