# Generated by Django 4.2.7 on 2024-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvators', '0002_chat_notes_remove_user_email_user_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='empid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
